num_1 = int(input("Ingrese el numero 1 "))
num_2 = int(input("Ingrese el numero 2 "))
num_3 = int(input("Ingrese el numero 3 "))
num_4 = int(input("Ingrese el numero 4 "))
num_5 = int(input("Ingrese el numero 5 "))
num_6 = int(input("Ingrese el numero 6 "))
num_7 = int(input("Ingrese el numero 7 "))
num_8 = int(input("Ingrese el numero 8 "))
num_9 = int(input("Ingrese el numero 9 "))
num_10 = int(input("Ingrese el numero 10 "))

numbers = []
numbers.append(num_1)
numbers.append(num_2)
numbers.append(num_3)
numbers.append(num_4)
numbers.append(num_5)
numbers.append(num_6)
numbers.append(num_7)
numbers.append(num_8)
numbers.append(num_9)
numbers.append(num_10)

high_number = max(numbers)
print(str(numbers) + ". El más alto fue " + str(high_number))
